### ISSUE TITLE
Hardcoded working path

### ISSUE THREAD

**Issue by xerz-one** [isovector/design-tools#3]
The following absolute working path has been hardcoded in the source code, requiring all projects to emit code into it:

https://github.com/isovector/design-tools/blob/c55747a9dbcbe7df8a438760846387d4dcf47ff6/src/AgdaDump.hs#L206-L207

This can be reproduced by e.g. compiling Certainty by Construction, where the command `pandoc -F pandoc-crossref --citeproc --filter design-tools-exe --from markdown+fancy_lists+raw_tex+raw_html --bibliography=bibliography.bib -M link-citations --tab-stop=100 --no-highlight --top-level-division=part -t latex+lagda -o build/tex/agda/Chapter1-Agda.lagda.tex src/book/Chapter1-Agda.lagda.md` will return the following error:

```console
design-tools-exe: /home/sandy/prj/math-for-programmers/build/tex/agda/Chapter1-Agda-dump.lagda.tex: withFile: does not exist (No such file or directory)
```

Relative paths should instead be used accordingly, as to support any tree input.

**Comment by isovector** [comment]
This is an internal tool that comes without, as they say, any warranty! You're welcome to work around the issue, but it's not in my financial best interests to make this book *too* easy to build :)
